// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Steema.TeeChart;

namespace Xplore_Lite
{
	public partial class DistrDevTypController : UIViewController
	{
		// Creating a sample Tee chart 
		// With a static Data Set - Pie
		public TChart chart1 = new Steema.TeeChart.TChart();
		
		System.Drawing.RectangleF r1;
		
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			chart1.Frame = DDTUIView.Frame;
			this.View.AddSubview(chart1);
			
			// Bar series
			Steema.TeeChart.Styles.Pie pie1 = new Steema.TeeChart.Styles.Pie();  
			chart1.Series.Add(pie1);
			chart1.Aspect.View3D = true;
			
			// Header
			chart1.Header.Text = "Distribution by Device Type";
			chart1.Header.Visible = false;
			chart1.Header.Alignment = MonoTouch.CoreText.CTTextAlignment.Center;
			chart1.Header.Shadow.Visible = true;
			
			// Formating Legend
			chart1.Legend.Alignment = LegendAlignments.Bottom;
			chart1.Legend.Shadow.Visible=false;
			chart1.Legend.Transparency = 50; 
			
			// Static series
			pie1.Add(66,"Smart Phone",UIColor.Blue.CGColor);  
			pie1.Add(21,"USB Modem",UIColor.Red.CGColor);  
			pie1.Add(8,"Wireless Hotspot",UIColor.Green.CGColor);  
			pie1.Add(5,"Others",UIColor.Yellow.CGColor);

		}
		
		public override void DidRotate(UIInterfaceOrientation fromInterfaceOrientation) 
		{
			// Refresh Chart rotating the device
			r1 = new System.Drawing.RectangleF(0,0,this.View.Bounds.Width/2,this.View.Bounds.Height/2);						
			chart1.Frame = r1;
			
		}
		
		public override bool ShouldAutorotateToInterfaceOrientation (UIInterfaceOrientation toInterfaceOrientation)
		{
			// Return true for supported orientations			
			return true;
		}
		
		public DistrDevTypController (IntPtr handle) : base (handle)
		{
		}
	}
}


