// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Xplore_Lite
{
	public partial class MainViewController : UIViewController
	{
		public MainViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			//Assign images to Launch buttons
			this.buttonSAxM.SetImage(UIImage.FromFile ("Images/SAxM_238x31.png"), UIControlState.Normal);
			this.buttonSAxC.SetImage(UIImage.FromFile ("Images/SAxC_238x31.png"), UIControlState.Normal);
		}
	}
}
