// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;
using System.Drawing;
using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Xplore_Lite
{


	public partial class MainViewController : UIViewController
	{
		//UIButton buttonSaxM;

		public MainViewController (IntPtr handle) : base (handle)
		{

		}


		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			// Code to create a new button and add image programmatically 
			//buttonSaxM = UIButton.FromType(UIButtonType.RoundedRect);
			//buttonSaxM.SetImage(UIImage.FromFile ("Images/SAxM_238x31.png"), UIControlState.Normal);
			//buttonSaxM.SetImage(UIImage.FromFile ("Images/SAxM_238x31.png"), UIControlState.Disabled);
			//buttonSaxM.Frame = new RectangleF(70, 20,180, 42);
			//View.AddSubview (buttonSaxM);

			buttonSaxMLaunch.SetImage(UIImage.FromFile ("Images/SAxM_238x31.png"), UIControlState.Normal);
			buttonSaxCLaunch.SetImage(UIImage.FromFile ("Images/SAxC_238x31.png"), UIControlState.Normal);
		}
	}
}
