// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Xplore_Lite
{

	public partial class MonkeyController : UIViewController
	{

		public MonkeyController (IntPtr handle) : base (handle)
		{
		}
		/// <summary>
		/// Partial method for the Connection created in the Storyboard
		/// </summary>
		partial void clicked (MonoTouch.Foundation.NSObject sender)
		{
			Console.WriteLine("Back to Main pressed");
			DismissModalViewControllerAnimated(true);
		}
	}
}